format_version: 4
pipelines:
  "prm-gp2gp-dashboard":
    group: gp2gp
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-test
            npm_build:
              resources:
                - docker
              artifacts:
                - build:
                    source: public
                - build:
                    source: .cache
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-get-metrics
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-get-metadata
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-build dev
      - deploy:
          clean_workspace: true
          jobs:
            gastby_deploy:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: npm_build
                    source: public
                - fetch:
                    stage: build
                    job: npm_build
                    source: .cache
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-deploy
