format_version: 4
pipelines:
  "prm-gp2gp-dashboard":
    group: gp2gp
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-test
      - build_dev:
          clean_workspace: true
          npm_build:
            resources:
              - docker
            artifacts:
              - build:
                  source: public
              - build:
                  source: .cache
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks dojo-get-metrics dev
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks dojo-get-metadata dev
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks dojo-build dev
      - deploy_dev:
          clean_workspace: true
          jobs:
            gastby_deploy:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build_dev
                    job: npm_build
                    source: public
                - fetch:
                    stage: build_dev
                    job: npm_build
                    source: .cache
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-deploy
      - build_prod:
          clean_workspace: true
          npm_build:
            resources:
              - docker
            artifacts:
              - build:
                  source: public
              - build:
                  source: .cache
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks dojo-get-metrics prod
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks dojo-get-metadata prod
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks dojo-build prod
      - deploy_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            gastby_deploy:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build_prod
                    job: npm_build
                    source: public
                - fetch:
                    stage: build_prod
                    job: npm_build
                    source: .cache
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-deploy
