format_version: 4
pipelines:
  "prm-gp2gp-dashboard":
    group: gp2gp
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-test
      - test_e2e:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              artifacts:
                - build:
                    source: e2e/videos
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-get-stubs
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-build dev
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-test-e2e
      - build_and_publish_docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - IMAGE_TAG=$GO_PIPELINE_LABEL ./tasks publish-docker
